version: "3.7"

services:
  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    working_dir: /home/node/app
    entrypoint: "npm run dev"
    stdin_open: true
    tty: true
    volumes:
      - ./bot:/home/node/app
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}